[features]
seeds = false
skip-lint = false

[programs.localnet]
zyncx = "6Qm7RAmYr8bQxeg2YdxX3dtJwNkKcQ3b7zqFTeZYvTx6"

[programs.devnet]
zyncx = "6Qm7RAmYr8bQxeg2YdxX3dtJwNkKcQ3b7zqFTeZYvTx6"

[registry]
url = "https://api.apr.dev"

[provider]
# For testing use localnet, for deployment use devnet
cluster = "Localnet"
# cluster = "devnet"  # Uncomment for devnet deployment
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.30.1"

[workspace]
members = ["contracts/solana/*"]

