[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
zyncx = "CVq4XNG8mtrBCvBawm1PRSSa72Dew9yy1rC9C25zJqh3"

[programs.localnet]
zyncx = "CVq4XNG8mtrBCvBawm1PRSSa72Dew9yy1rC9C25zJqh3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["contracts/solana/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 60000
shutdown_wait = 5000
upgradeable = false
